### ISSUE TITLE
[✨New Test] Load config visually

### ISSUE THREAD

**Issue by giladbarnea** [idotavorslab/PYANO#14]

**Comment by ShacharGal** [comment]
this only happens after refresh
maybe we can add an automatic refresh after loading?

**Comment by giladbarnea** [comment]
Can you specify steps to reproduce?
I.e "I launched Pyano by double clicking the icon on the desktop, the first page that was loaded was New Test and the config didn't load visually. I needed to refresh for it to happen."
Can't reproduce it on my machine here...
