### ISSUE TITLE
Record page doesn't show / doesn't let me play all files, what gives?

### ISSUE THREAD

**Issue by idotavorslab** [idotavorslab/PYANO#2]

**Comment by idotavorslab** [comment]
Only files that have a .mid file and a .txt file with the same name are displayed.
We need both to play them correctly

**Comment by ShacharGal** [comment]
and when is the .mid file created? why was I unable to play the full fur_elis there?

**Comment by idotavorslab** [comment]
Right now, a .txt file with no midi twin is created when starting a test (internally called "inside test page"). This only applies to the current chosen truth file.

I will make it happen automatically to all "orphan" txt files when entering record page.

Please click "Close issue" below when read.
