### ISSUE TITLE
"We'll show you what notes you got wrong" text is misleading

### ISSUE THREAD

**Issue by giladbarnea** [idotavorslab/PYANO#20]
כשמישהו טועה, לפני שהאנימציה עולה כתוב שנראה לו את הטעויות שלו, אבל בעצם, זה לא נכון - אנחנו מראים לו איפה הוא טעה על גבי האמת. אז צריך לשנות את זה ל״הנה נראה לך איפה טעית״

**Comment by idotavorslab** [comment]
here's the animation again highlighting where you got it wrong this time

**Comment by giladbarnea** [comment]
Done
