### ISSUE TITLE
Aesthetic notes by Ido

### ISSUE THREAD

**Issue by giladbarnea** [idotavorslab/PYANO#22]
האנימציה יוצאת נורא נמוך במסך, אפשר למרכז את זה?
במסך של new test יש מלא חלל ריק משמאל, אולי אחרי שנסיים הכל אפשר לסדר קצת מחדש את המקשים במסך הזה כדי שיהיה קצת יותר מסוגנן

**Comment by idotavorslab** [comment]
sagur
