### ISSUE TITLE
What do I do if I don't want DevTools opening at the side?

### ISSUE THREAD

**Issue by idotavorslab** [idotavorslab/PYANO#4]

**Comment by idotavorslab** [comment]
## Answer:
It is now conditioned with this field:
![image](https://user-images.githubusercontent.com/48498791/54275743-246b5100-4594-11e9-84b0-36722191728e.png)

In the future there will be a GUI button to toggle it on / off.

**Comment by ShacharGal** [comment]
coolness

**Comment by ShacharGal** [comment]
this doesn't still apply, right?
any way for me to change something so it wont pop?

**Comment by giladbarnea** [comment]
Fixed in https://github.com/idotavorslab/PYANO/commit/190c638ea7fd225879c7c23bfe82801d79a222fe
