### ISSUE TITLE
"Full" full screen

### ISSUE THREAD

**Issue by giladbarnea** [idotavorslab/PYANO#43]
Hide the taskbar? 
![image](https://user-images.githubusercontent.com/18548473/55709895-03aae580-59f2-11e9-9410-0e3c106240e4.png)

Hide the menu?
![image](https://user-images.githubusercontent.com/18548473/55710116-8e8be000-59f2-11e9-98d7-75a41f66d07a.png)

Both?

**Comment by ShacharGal** [comment]
taskbar
