### ISSUE TITLE
telling windows not to be annoying

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#48]
how do i stop windows from prompting updates while pyano is on? this is annoying and creates lags

**Comment by giladbarnea** [comment]
This is not a Pyano issue. You should limit windows "active hours". 
Windows key => "active hours" => change to something like this:
![image](https://user-images.githubusercontent.com/18548473/56090733-bd9cc880-5eae-11e9-8e9d-8d6c5313662c.png)

I heard next major windows update will introduce an option to opt out of future updates
