### ISSUE TITLE
No way to "remove level" after adding

### ISSUE THREAD

**Issue by idotavorslab** [idotavorslab/PYANO#5]

**Comment by idotavorslab** [comment]
## Answer:

One direct solution is to have a "remove level" button.

Another semi-direct solution, which will be resolved regardless, is to save a config and auto-load it based on truth file. It is a semi-solution because you could save your current config, and if accidentally pressed "add level", you would ctrl+r and the last saved config would load.

On the very short term, which solution do you want resolved first? The "remove level" button?

**Comment by ShacharGal** [comment]
yeah, I think the remove level button should be a must
could be even better if it's a '-' sign near the level itself.

**Comment by idotavorslab** [comment]
I'm implementing a "remove last level" button, in the future there may be a minus sign besides each level.
