### ISSUE TITLE
slowing down tempo

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#50]
adding an option to slow down tempo to create levels of tempo lerning.
- is possible for video as well?
- what is your opinion on the effect on learning (ido's mail)
on sunday i have a meeting with ido and we will discuss this, so if we can get a small example of how the slowed down video can be, and you opinion on the matter, it'll be great

**Comment by giladbarnea** [comment]
Discussed in email, here's the original message for ease of access:
![image](https://user-images.githubusercontent.com/18548473/56092735-4d02a580-5ec8-11e9-97e2-35f851b6160e.png)
