### ISSUE TITLE
[🎹 Inside Test] Post trial animation should only happen if there are accuracy and/or rhythm mistakes. Won't happen if only tempo mistakes.

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#57]
first of all, for some reason it currently plays the error animations with the slow-down factor, which is not supposed to happen in tempo mode.

moreover, the current set-up got me thinking that maybe we **don't need** the post animation for tempo levels??
because even when there is a tempo error, the post animation usually doesn't really provide any information about the error (ass opposed to an accuracy error animation, which does provide beneficial information). if you tell the subject that he played "too slow" or "too fast", its enough. and reducing the amount of demos could be good, because currently its a bit hectic. 
perhaps only **rhythm errors** should still be shown. and see issue #61 suggesting they should maybe be in blue, so to differentiate from acc errors

that being said, when an accuracy error shows up during tempo mode, it should still show the error animation. (also, see issue #61)

what do you think?

**Comment by giladbarnea** [comment]
The discussion about the playback speed is here:
https://github.com/idotavorslab/PYANO/issues/61#issuecomment-489594493

Back to the flow issue, tell me if this captures what you said well:
If user got accuracy and rhythm right, but got the tempo wrong (too fast or too slow), **don't** show an error animation. Textual feedback is enough.
If user got accuracy and rhythm wrong, **show** an error animation. Text may include "too fast / slow" if needed.

The **contents** of the error animation are discussed here:
https://github.com/idotavorslab/PYANO/issues/61#issuecomment-489594493

**Comment by ShacharGal** [comment]
Yup

**Comment by giladbarnea** [comment]
This was summarized in the [Demos project](https://github.com/idotavorslab/PYANO/projects/1#card-21108156)
