### ISSUE TITLE
Tempo testing feels too strict

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#60]
following our conversations on this matter, I strongly think we should add a tempo deviation factor.
currently it feels like it can be too strict at times for playing a little to fast or too slow, and I don't want to "rape" the rhythm deviation factor to much in order to enable a realistic error interval

**Comment by giladbarnea** [comment]
I have a feeling something's unclear to you with Pyano's current behavior, correct me if I'm wrong.
When setting a level with tempo = 50%, the subject can play anywhere between 50% speed and 100% and that's fine. He passes as long as the rhythm and accuracy are right, even if he played at 50% speed, 75% speed, 100% speed etc.
This is a wide margin for mistake, so I'm assuming you didn't mean to widen it further.

If so, did you feel like it's too strict when the level is set with tempo = 100%?
In that case, the deviation margin is automatically set to anywhere between 90% and 100%.
We can make it a parameter under your control, but I feel like it's better if we just find a "golden" range and hard code it. 
I.e, maybe allowing 80% to 110% feels like the right level of strictness, when testing for tempo = 100%.

Thoughts?

**Comment by ShacharGal** [comment]
I felt that o got "too slow" for 80%, even though I was quite spot on.
Maybe I was 78%....
That's too strict

**Comment by giladbarnea** [comment]
![image](https://user-images.githubusercontent.com/18548473/57232750-f18a8a00-7025-11e9-9f2e-28d786125a1d.png)
Done
