### ISSUE TITLE
[🎹 Inside Test] Making tempo error text more encouraging 

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#62]
in the current set up, the subject gets to the tempo mode shortly after learning the notes, and even if they just succeed the accuracy, they should be somehow encouraged, and verbally rewarded. the oi vei might be a bot harsh on them
maybe something in the lines of "good job on the accuracy, but you timing\rhythm is still a bit off"

**Comment by giladbarnea** [comment]
OK.
In other words: "if previous level was accuracy, and this level is tempo, and this is the first trial within that level, and the subject got the rhythm wrong, make the text more encouraging".
So for example, let's assume:
```
Level 0 is accuracy
    trial 0
    trial 1
Level 1 is tempo. 
    trial 0
    trial 1
```
Then if subject had good accuracy but bad rhythm in Level 1 Trial 0, the "encouraging" text should appear.

Sounds good?

**Comment by ShacharGal** [comment]
I think generally it should point out and encourage whenever note accuracy
was good :)
