### ISSUE TITLE
Add "Exam" page (in contrast with "New Test")

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#63]
in several points in our process we need to preform a"test".
this is done in the beginning and in the end, with the two novel pieces we composed, and also in the end we will test for higher speeds.

this needs to be similar to current tempo mode, with two changes:
1) you don't get a second try if you had accuracy mistakes
2) the messages should be different ("this is a test, you will be playing in X speed, good luck)

**Comment by giladbarnea** [comment]
This is not entirely clear to me; 

> this is done in the beginning and in the end, with the two novel pieces we composed, and also in the end we will test for higher speeds.

In other words: 
Typically, "test mode" will be used twice: first thing before the learning begins, and in the end after learning 'completed'. Note that the test in the end (unlike the one in the beginning) will test for >100% speeds.
Is this correct?

Thing I need explaining:
1. Why do you need this mode? What is it used for?
2. Are you OK with Test mode having the same "tempo" drop-down selection as with "rhythm-positive" levels? (I'm assuming that you do)
3. Should I disable the option to specify a number of trials for Test mode? (ie force only 1 trial) 
4. Are you OK with Test mode having the same "notes" drop-down selection as with other modes?

**Comment by ShacharGal** [comment]
i'm not really sure what wasn't clear, so ill start explaining from scratch.

there is a scenario in which we wan to TEST and not TRAIN. 
in our current design it happens in the first and last sessions (at first - a novel piece from those we both composed, at the and, another novel piece, and furls fast) , but the timing has no importance in regards to writing the feature. it should be in session of its own (with its own config and so on)

these are the features it should have
1) ability to determine speed ratio (just like in current tempo mode, bet with a range of >100%). in this aspect, I'm OK with your (2) point in your comment.
2) as opposed to "training-tmpo-mode", it should not give a second try when there is an accuracy error. 
3) you should not disable the option for number of trials, because we might want to give someone X chances to complete the test.
4) im OK with Test mode having the same "notes" drop-down selection as with other modes
5) messages should be in concordance with this being a test.

**Comment by ShacharGal** [comment]
closed issue and opened some new ones instead
