### ISSUE TITLE
[🎹 Inside Test] Pre-trial and Post-trial demo flow changes

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#64]
because we have now more levels for each N notes, it could get quite tedious to hear so many demos, and also un-efficient, because the subject listens to demos more than he plays the piano. and also, the tutorial gets really long....

two things we should change:

1) the first tempo level that comes after the acc level, is in the same speed, so there is no need to show the video again. maybe this could be easier for you to do along with grouping all levels with N notes to one level, with sub levels that are different in speed or learning type.

2) this is a more dramatic change - I thing we should drop the pre-trial animation. by this I mean that of course when you begin a level you will have an animation, but from than we will have only the post-trial animation (with or without errors), and then straight to the next trial.

**Comment by giladbarnea** [comment]
Help me "formulate" the points.
> 1. the first tempo level that comes after the acc level, is in the same speed, so there is no need to show the video again.

Is this equivalent to,
"Don't show the pre-trial video of a trial if it has the same speed as the previous trial"?

About the 2nd point, I need to think about it a bit more to form a confident opinion.
Unless you and Ido have already decided to drop it?

**Comment by ShacharGal** [comment]
after consulting with Ido:

- Pre trial animation will only occur if its the first in a level. actually, we can just refer to it as the "beginning of level" animation. 
- Post trial animation will only happen if there are mistakes (accuracy or rhythm, no speeding error animations, see issue #57). this means that if you got it absolutely right in a trial, you won't see another animation before playing again (unless it was the last trial in this level, and then you'll have the next levels demonstrations before playing again).
- when starting a new level, if the last level had the same N and speed (but was testing for accuracy), do not show video again (do show animation, so to have some "separation" between levels)

I think this covers everything. if I missed something, ask and we'll clear it up.

**Comment by giladbarnea** [comment]
OK, thanks.
 > when starting a new level, if the last level had the same N and speed (but was testing for accuracy), do not show video again (do show animation, so to have some "separation" between levels).

I'm going to implement it likewise: "when starting a new level, if the last level had the same N and speed (_but was testing for a different mode than current one_), do not show video again (do show animation, so to have some 'separation' between levels)."
Is this OK?

**Comment by ShacharGal** [comment]
"(but was testing for a different mode than current one)"
this actually doesn't really have to be regarded in the code, because then it will be exactly similar levels, wouldn't it? 
but it wouldn't hurt either...

**Comment by giladbarnea** [comment]
For the sake of order, this issue's contents were summarized in [Demoes project](https://github.com/idotavorslab/PYANO/projects/1) Project
