### ISSUE TITLE
export information

### ISSUE THREAD

**Issue by ShacharGal** [idotavorslab/PYANO#83]
previously you mentioned you can export some data you have when you analyse a trial. but I didn't see an issue about it so I opened one.

I kinda figured out how to deal with acc mistakes, but when it comes to tempo, I could with some data that you probably have
1) passed or not
2) if not, was it a rhythm or tempo failure
3) if only tempo, how far off was it? 
4) if rhythm, how many mistakes? was the tempo ok? if tempo also not ok, then how far off?

**Comment by giladbarnea** [comment]
Comment migrated to https://github.com/idotavorslab/PYANO/issues/68
